name: "Telert Run"
description: "Get notified on Telegram, Slack, Teams, Pushover (Android / iOS), Desktop when terminal commands finish — powered by Telert"
author: "Mihir Khandekar"

branding:
  icon: "bell"
  color: "purple"

inputs:
  command:
    description: "Shell command to execute"
    required: true
  label:
    description: "Label shown in the notification"
    default: "GitHub Action"
  provider:
    description: "Comma-separated provider list (e.g. slack,telegram)"
    required: false
    default: ""               # empty string by default

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install Telert
      shell: bash
      run: pip install --no-cache-dir telert

    - name: Run command with Telert
      shell: bash
      run: |
        CMD="${{ inputs.command }}"
        LABEL="${{ inputs.label }}"
        PROVIDER="${{ inputs.provider }}"

        # Build optional flag only if provider was supplied
        if [ -n "$PROVIDER" ]; then
          PROVIDER_ARG="--provider $PROVIDER"
        fi

        # Execute the user's command and pipe the output to Telert
        eval "$CMD" | telert "$LABEL" ${PROVIDER_ARG:-}
